### ISSUE TITLE
GtkSettings error in browser.js

### ISSUE THREAD

**Issue by benwaffle** [WebReflection/node-gtk#25]
``` JS
/tmp/node-gtk/examples/browser.js:44
    gtkSettings.set_property('gtk-application-prefer-dark-theme', true);
                ^

TypeError: gtkSettings.set_property is not a function
    at /tmp/node-gtk/examples/browser.js:44:17
    at Object.<anonymous> (/tmp/node-gtk/examples/browser.js:113:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by WebReflection** [comment]
Thanks, it's fixed.
